---
- name: Install Java 21, Jenkins, Docker, Git, Node.js and Python on Azure VM
  hosts: azure_vms          # <-- match this to your inventory group
  become: yes

  vars:
    jenkins_repo_key_url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    jenkins_repo: "deb https://pkg.jenkins.io/debian-stable binary/"

  tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    #################################################################
    # Java 21
    #################################################################
    - name: Install OpenJDK 21 (Java 21)
      ansible.builtin.apt:
        name: openjdk-21-jdk
        state: present

    #################################################################
    # Jenkins
    #################################################################
    - name: Install Java 17 as Jenkins dependency (if needed)
      ansible.builtin.apt:
        name: openjdk-17-jdk
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Add Jenkins repository GPG key
      ansible.builtin.get_url:
        url: "{{ jenkins_repo_key_url }}"
        dest: /usr/share/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: Add Jenkins APT repository
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/jenkins.list
        content: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] {{ jenkins_repo }}\n"
        mode: '0644'

    - name: Update APT cache after adding Jenkins repo
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present

    - name: Ensure Jenkins is enabled and started
      ansible.builtin.service:
        name: jenkins
        state: started
        enabled: yes

    #################################################################
    # Docker
    #################################################################
    - name: Install Docker prerequisites
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker GPG key
      ansible.builtin.command: >
        bash -lc "install -m 0755 -d /etc/apt/keyrings && curl -fsSL https://download.docker.com/linux/ubuntu/gpg |
        gpg --dearmor -o /etc/apt/keyrings/docker.gpg"
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Add Docker APT repository
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/docker.list
        mode: '0644'
        content: |
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable

    - name: Update APT cache after adding Docker repo
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker Engine
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Ensure Docker is enabled and started
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    #################################################################
    # Git
    #################################################################
    - name: Install Git
      ansible.builtin.apt:
        name: git
        state: present

    #################################################################
    # Node.js
    #################################################################
    - name: Install Node.js and npm (Ubuntu repo version)
      ansible.builtin.apt:
        name:
          - nodejs
          - npm
        state: present

    #################################################################
    # Python
    #################################################################
    - name: Install Python 3 and pip
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
        state: present
